#!/usr/bin/env python

# for each config file
#   for each sysenv
#     create the sysenv if it doesn't exist
#     gather all requirements to install and their url and all symlinks
#     pip install the requirements
#     update/create all the symlinks

import sys
import yaml

config_files = sys.argv[1:]

for config_file in config_files:
    print(config_file)
    with open(config_file) as config_file_pointer:
        config = yaml.load(config_file_pointer)
        print(config)
        urls = []
        symlinks = []
        for sysvenv in config:
            for program in config[sysvenv]:
                data = config[sysvenv][program]
                try:
                    urls.append(data['url'])
                except KeyError:
                    urls.append(program)
                try:
                    symlinks.extend(data['symlink'])
                except KeyError:
                    symlinks.append(program)
        print(sysvenv, urls, symlinks)
