#!/usr/bin/env python

# for each config file
#   for each sysenv
#     create the sysenv if it doesn't exist
#     gather all requirements to install and their url and all symlinks
#     pip install the requirements
#     update/create all the symlinks

import sys

import yaml

from triforce import Virtualenv, parse_venv


config_files = sys.argv[1:]



def process_venvs():
    venvs = []
    for config_file in config_files:
        with open(config_file) as config_file_pointer:
            config = yaml.load(config_file_pointer)
            for name, venv in config.items():
                venvs.append(parse_venv(name, venv))
        return venvs

try:
    for venv in process_venvs():
        print(venv)
        venv.process()
except sh.ErrorReturnCode as e:
    print(e)
    print(e.stdout)
    print(e.stderr)
