#!/usr/bin/env python

# for each config file
#   for each sysenv
#     create the sysenv if it doesn't exist
#     gather all requirements to install and their url and all symlinks
#     pip install the requirements
#     update/create all the symlinks

import os
import sys
import shlex

import yaml
import sh


config_files = sys.argv[1:]

DEFAULT_VENV_PREFIX = os.environ['HOME']
DEAFULT_VENV_COMMAND = "python3"
DEFAULT_SYMLINK_PREFIX = os.path.join(os.environ['HOME'], 'bin')

class Virtualenv(object):

    def __init__(self, name,
                 venv_prefix=None,
                 venv_command=None,
                 urls=None,
                 symlink_prefix=None,
                 symlinks=None):
        self.name = name
        self.venv_prefix = venv_prefix or DEFAULT_VENV_PREFIX
        self.path = os.path.join(self.venv_prefix, self.name)
        self.venv_command = venv_command or DEAFULT_VENV_COMMAND
        self.urls = urls
        self.symlink_prefix = symlink_prefix or DEFAULT_SYMLINK_PREFIX
        self.symlinks = symlinks

    def __str__(self):
        return str(self.__dict__)

    def create(self):
        print("Creating venv at: '{0}'".format(self.path))
        if self.venv_command in [2, '2', 'py2', 'python2']:
            print(execute('virtualenv {0}'.format(self.path)))
        elif self.venv_command in [3, '3', 'py3', 'python3']:
            print(execute('pyvenv {0}'.format(self.path)))
        else:
            print(execute('{0} {0}'.format(self.venv_command, self.path)))
        print("'pip' command is: '{0}'".format(self.pip_path))

    def bootstrap_utilities(self):
        print("Installing/upgrading utilities: 'pip' and 'pybuilder'")
        self.pip_install('pip')
        self.pip_install('pybuilder')

    @property
    def bin_path(self):
        return os.path.join(self.path, 'bin')

    @property
    def pip_path(self):
        return os.path.join(self.bin_path, 'pip')

    def pip_install(self, stuff):
        print(execute("{0} install -U {1}".
                      format(self.pip_path, stuff)))

    def install_dependencies(self):
        urls_string = ' '.join(self.urls)
        print("Installing dependencies: '{0}'".format(self.urls))
        print(execute("{0} install {1}".
                      format(self.pip_path, urls_string)))

    def symlink(self):
        for link in self.symlinks:  # triforce... link...
            source = os.path.join(self.bin_path, link)
            target = os.path.join(self.symlink_prefix, link)
            print("Will symlink: '{0}' --> '{1}'".format(source, target))
            try:
                os.symlink(source, target)
            except FileExistsError:
                pass

    def process(self):
        self.create()
        self.bootstrap_utilities()
        self.install_dependencies()
        self.symlink()


def execute(command):
    p = shlex.split(command)
    c = sh.Command(p[0])
    return c(p[1:])


venvs = []
for config_file in config_files:
    with open(config_file) as config_file_pointer:
        config = yaml.load(config_file_pointer)
        for sysvenv_name, sysvenv in config.items():
            venv_command, venv_prefix, symlink_prefix = None, None, None
            urls, symlinks = [], []
            for program, options in sysvenv.items():
                if program == 'triforce':
                    try:
                        venv_command = options['venv_command']
                    except KeyError:
                        pass
                    try:
                        venv_prefix = options['venv_prefix']
                    except KeyError:
                        pass
                    try:
                        symlink_prefix = options['symlink_prefix']
                    except KeyError:
                        pass
                else:
                    try:
                        urls.append(options['url'])
                    except KeyError:
                        urls.append(program)
                    try:
                        symlinks.extend(options['symlink'])
                    except KeyError:
                        symlinks.append(program)
            venvs.append(Virtualenv(sysvenv_name,
                                    venv_prefix=venv_prefix,
                                    venv_command=venv_command,
                                    urls=urls,
                                    symlink_prefix=symlink_prefix,
                                    symlinks=symlinks))
for venv in venvs:
    print(venv)
    venv.process()
